### ISSUE TITLE
TypeError: 'AnimationVec2Targets' object is not iterable

### ISSUE THREAD

**Issue by MariallenaHax** [CLF78/Actually-Working-BREFF-Converter#1]
When I tested this program with MKW's rk_EnvSnow.breff, I got the above error.
Python version - 3.10.11

Full Error log
```
Traceback (most recent call last):
  File "C:\Users\rover\Actually-Working-BREFF-Converter\breff_decode.py", line 64, in <module>
    decode(src, dest)
  File "C:\Users\rover\Actually-Working-BREFF-Converter\breff_decode.py", line 46, in decode
    json_dump(effect_file, effect.to_json())
  File "C:\Users\rover\Actually-Working-BREFF-Converter\common\field.py", line 221, in to_json
    json_value = field.to_json(value)
  File "C:\Users\rover\Actually-Working-BREFF-Converter\common\field.py", line 417, in to_json
    return value.to_json() if value else {}
  File "C:\Users\rover\Actually-Working-BREFF-Converter\animations\anim.py", line 43, in to_json
    return super().to_json()
  File "C:\Users\rover\Actually-Working-BREFF-Converter\common\field.py", line 221, in to_json
    json_value = field.to_json(value)
  File "C:\Users\rover\Actually-Working-BREFF-Converter\common\field.py", line 488, in to_json
    return [self.item_field.to_json(item) for item in value]
  File "C:\Users\rover\Actually-Working-BREFF-Converter\common\field.py", line 488, in <listcomp>
    return [self.item_field.to_json(item) for item in value]
  File "C:\Users\rover\Actually-Working-BREFF-Converter\common\field.py", line 417, in to_json
    return value.to_json() if value else {}
  File "C:\Users\rover\Actually-Working-BREFF-Converter\common\field.py", line 221, in to_json
    json_value = field.to_json(value)
  File "C:\Users\rover\Actually-Working-BREFF-Converter\common\field.py", line 417, in to_json
    return value.to_json() if value else {}
  File "C:\Users\rover\Actually-Working-BREFF-Converter\animations\types\f32.py", line 358, in to_json
    for i, target_name, target_value in get_enabled_targets(sub_targets):
  File "C:\Users\rover\Actually-Working-BREFF-Converter\animations\common.py", line 30, in get_enabled_targets
    for i, entry in enumerate(sub_targets):
TypeError: 'AnimationVec2Targets' object is not iterable
```

**Comment by CLF78** [comment]
Thank you for reporting. It looks like iterating enums was added in Python 3.11 and Vermin somehow missed that. I tested the file and it is working on my end, so upgrading to Python 3.11 should do the trick.

**Comment by MariallenaHax** [comment]
```
Traceback (most recent call last):
  File "C:\Users\rover\Actually-Working-BREFF-Converter\breff_decode.py", line 64, in <module>
    decode(src, dest)
  File "C:\Users\rover\Actually-Working-BREFF-Converter\breff_decode.py", line 35, in decode
    json_dump(meta_file, header.to_json())
  File "C:\Users\rover\Actually-Working-BREFF-Converter\common\common.py", line 25, in json_dump
    json.dump(data, path, separators=(',', ': '), indent=2)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
    ^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute 'write'. Did you mean: 'drive'?
```

When I tried it with the Microsoft Store version of Python 3.11, I got a different error this time.

**Comment by CLF78** [comment]
Okay, looks like i botched the dumping part without the orjson package. Thanks for reporting, i have committed a fix, you should get it to work now.

**Comment by MariallenaHax** [comment]
sorry too late, it works thanks!
